name: mask_for_camera_view_example
description: Demonstrates how to use the mask_for_camera_view plugin.

publish_to: 'none' 

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  mask_for_camera_view:
    path: ../
  cupertino_icons: ^1.0.6
  url_launcher: ^6.2.3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.4

  
  
flutter_icons:
  android: true
  ios: true
  image_path: 'lib/assets/logo.png'

flutter:

  uses-material-design: true
